version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=258258258
      - DB_NAME=Iocanalysis
    depends_on:
      - db
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"] 
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=258258258
      - POSTGRES_DB=Iocanalysis
